import Head from "next/head";
import Masthead from "../components/Masthead";
import Card from "../components/Card";
import Contact from "../components/Contact";
import Content from "../components/Content";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Masthead />
      <Content />
      <Card />
      <Contact />

      <footer className={styles.footer}>
        <p>
          Copyright © 2021 Pinksale Pros | Serving our customers since 2021 |
          Website made by Pinksale Pros
        </p>
      </footer>
    </div>
  );
}
